app/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func
from flask_bcrypt import generate_password_hash, check_password_hash

db = SQLAlchemy()

# # 認証ユーザーの呼び出し方を定義します
def load_user(user_id):
    return User.query.get(int(user_id))

# Userテーブルの定義
class User(UserMixin, db.Model):
    __tablename__ = 'users'

    # カラム定義
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), index=True)
    password = db.Column(db.String(128))
    created_at = db.Column(db.DateTime, server_default=func.now(), nullable=False)

    # Userクラスをインスタンス化した時に各カラムを引数として使えるように設定します
    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password = generate_password_hash(password)

    # 入力されたパスワードとハッシュ化されたパスワードを比較して検証する
    def validate_password(self, password):
        return check_password_hash(self.password, password)
    
    # メールアドレスからユーザーを検索する
    @classmethod
    def select_by_email(cls, email):
        return cls.query.filter_by(email=email).first()

class Task(db.Model):
    __tablename__ = 'tasks'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64), nullable=False)
    description = db.Column(db.String(256))
    endtime = db.Column(db.DateTime, nullable=False)
    created_at = db.Column(db.DateTime, server_default=func.now(), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, title, description, endtime, user_id):
        self.title = title
        self.description = description
        self.endtime = endtime
        self.user_id = user_id

app/app.py
from flask import Flask
import logging
from flask_login import LoginManager

from models import load_user, db
from views import bp

app = Flask(__name__)

# データベースとの接続の設定を定義
app.config['SQLALCHEMY_DATABASE_URI'] = \
  'mysql+mysqlconnector://{user}:{password}@{host}/{db_name}?charset=utf8'.format(**{
  'user': "user",
  'password': "password",
  'host': "db",
  'db_name': "todo_app"
  })

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = 'SECRET'

db.init_app(app)

logging.basicConfig(level=logging.DEBUG) 

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.user_loader(load_user)
login_manager.login_view = "root.login"

# ルーティングの設定
app.register_blueprint(bp)

if __name__ == "__main__":
    with app.app_context():  
        db.create_all()       
    app.run(host="0.0.0.0", debug=True)

app/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, logout_user, current_user
import mysql.connector

# 自分で作ったファイルからインポート
from models import User, db

bp = Blueprint("root", __name__, url_prefix="/")

# DBとの接続を確認するため （ヘルスチェック）
@bp.route("/db")
def db_test():
    conn = mysql.connector.connect(
        host="db",
        user="user",
        password="password",
        database="todo_app"
    )
    cursor = conn.cursor()
    cursor.execute("SELECT 1")
    result = cursor.fetchone()
    cursor.close()
    conn.close()

    if result[0] == 1:
        return "DBとの接続に成功しました"
    else:
        return "DBとの接続に問題が発生しました"

@bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == 'GET':
        return render_template('user_register.html')
    
    if request.method == 'POST':
        # 書き込まれた項目formから取得する
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')

        user = User(
            email = email,
            username = username,
            password = password
        )

        if User.select_by_email(email) != None:
            flash("このメールアドレスは既に登録されています", "danger")
        else:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('root.login'))
    return render_template('user_register.html')


@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.select_by_email(email)
        if user and user.validate_password(password):
            login_user(user)
            return redirect(url_for("root.home"))
        else:
            flash("メールアドレスまたはパスワードが間違っています", "danger")
            return redirect(url_for("root.login"))

@bp.route("/", methods=["GET"])
@login_required
def home():
    return render_template("home.html")

app/templates/_header.html
<header class="bg-white border-b-2 border-gray-300">
  <div class="py-2 flex items-center">
    <div class="p-4 rounded-full ml-4 bg-indigo-200 my-2">
      <a href="/" class="text-indigo-600 font-extrabold text-2xl">Todo APP</a>
    </div>
    <div class="flex items-center absolute right-8">
      <div class="flex items-center space-x-4 ml-4">
        <a
          href="{{ url_for('root.task_register') }}"
          class="bg-indigo-500 hover:bg-indigo-600 text-white font-bold p-4 rounded-full"
          >タスク追加</a
        >
      </div>
      <div class="flex items-center space-x-4 ml-4">
        <a
          href="{{ url_for('root.login') }}"
          class="border-2 border-indigo-300 hover:bg-gray-200 text-gray-500 font-bold p-4 rounded-full"
          >ログアウト</a
        >
      </div>
    </div>
  </div>
</header>

app/templates/home.html
{% extends "layout.html" %} {% block content %}

<div class="container mx-auto min-h-screen flex justify-center pt-24">
  <div class="container w-1/2 mx-auto px-4">
    <div class="grid grid-cols-1 gap-4 mt-6">
      {% for task in tasks %}
      <div class="bg-white p-4 rounded-lg shadow hover:bg-gray-100">
        <div class="flex justify-between">
          <div>
            <h2 class="text-2xl font-bold text-gray-600">{{ task.title }}</h2>
            <p class="text-gray-500">期限：{{ task.endtime }}</p>
          </div>
          <div class="flex space-x-2 text-sm">
            <a
              href="task/detail/{{ task.id }}"
              class="border-2 border-indigo-300 hover:bg-gray-200 text-gray-500 font-bold p-4 rounded-2xl"
              >詳細</a
            >
            <a
              href="task/update/{{ task.id }}"
              class="border-2 border-indigo-300 hover:bg-gray-200 text-gray-500 font-bold p-4 rounded-2xl"
              >編集</a
            >
            <a
              href="task/delete/{{ task.id }}"
              class="bg-indigo-400 hover:bg-indigo-500 text-white font-bold p-4 rounded-2xl"
              >完了</a
            >
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <title>Todo APP</title>
  </head>
  {% include "_header.html" %}
  <body>
    <div class="bg-gray-100">{% block content %} {% endblock content %}</div>
  </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <title>ログイン</title>
  </head>
  <main>
    <div class="min-h-screen flex items-center justify-center">
      <div class="bg-white p-10 rounded shadow-lg w-full md:w-1/3">
        <h1 class="text-2xl font-semibold mb-6">ログイン</h1>
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %}
        <div
          class="rounded bg-red-200 border-red-500 text-red-900 border-l-4 p-4 mb-4"
          role="alert"
        >
          <p>{{ message }}</p>
        </div>
        {% endfor %} {% endif %} {% endwith %}
        <form action="{{ url_for('root.login') }}" method="post">
          <div class="mb-4">
            <label class="block mb-1 text-gray-700">Email</label>
            <input
              type="email"
              name="email"
              placeholder="メールアドレスを入力"
              required
              class="w-full border border-gray-300 rounded py-2 px-3 focus:outline-none focus:border-indigo-500"
            />
          </div>
          <div class="mb-4">
            <label class="block mb-1 text-gray-700">パスワード</label>
            <input
              type="password"
              name="password"
              placeholder="パスワードを入力"
              required
              class="w-full border border-gray-300 rounded py-2 px-3 focus:outline-none focus:border-indigo-500"
            />
          </div>
          <div class="flex justify-between items-center pt-4">
            <button
              type="submit"
              class="bg-indigo-500 hover:bg-indigo-600 text-white font-bold p-4 rounded-full"
            >
              ログイン
            </button>
            <div class="flex items-center">
              <span class="text-gray-600">ユーザー登録がまだの方は</span>
              <a
                href="{{ url_for('root.register') }}"
                class="ml-2 text-indigo-500 hover:text-indigo-600 font-bold"
                >新規登録</a
              >
            </div>
          </div>
        </form>
      </div>
    </div>
  </main>
</html>

app/templates/task_detail.html
{% extends 'layout.html' %} {% block content %}
<div
  class="container mx-auto min-h-screen flex justify-center items-start pt-24"
>
  <div class="bg-white w-full max-w-md p-8 rounded-md shadow">
    <h1 class="text-2xl font-bold mb-6 text-gray-600">タスク詳細</h1>
    <div class="mb-4">
      <label for="endtime" class="block text-gray-700 mb-2">タスク名</label>
      <div
        class="bg-gray-100 rounded-lg border-2 border-indigo-300 p-4 font-bold text-gray-500"
      >
        <p>{{ task.title }}</p>
      </div>
    </div>
    <div class="mb-4">
      <label for="endtime" class="block text-gray-700 mb-2">詳細</label>
      <div
        class="bg-gray-100 rounded-lg border-2 border-indigo-300 p-4 font-bold text-gray-500"
      >
        <p>{{ task.description }}</p>
      </div>
    </div>
    <div class="mb-4">
      <label for="endtime" class="block text-gray-700 mb-2">期限</label>
      <div
        class="bg-gray-100 rounded-lg border-2 border-indigo-300 p-4 font-bold text-gray-500"
      >
        <p>{{ task.endtime.strftime('%Y-%m-%d') }}</p>
      </div>
    </div>
    <div class="flex justify-between items-center pt-4">
      <a
        href="{{ url_for('root.task_update', task_id=task.id) }}"
        class="bg-indigo-500 hover:bg-indigo-600 text-white font-bold p-4 rounded-full"
        >編集する</a
      >
      <a href="{{ url_for('root.home') }}" class="text-indigo-500">戻る</a>
    </div>
  </div>
</div>
{% endblock %}

app/templates/task_register.html
{% extends 'layout.html' %} {% block content %}
<div
  class="container mx-auto min-h-screen flex justify-center items-start pt-24"
>
  <div class="bg-white w-full max-w-md p-8 rounded-md shadow">
    <h1 class="text-2xl font-bold mb-6 text-gray-600">タスク作成</h1>
    <form action="{{ url_for('root.task_register') }}" method="POST">
      <div class="mb-4">
        <label for="title" class="block text-gray-700 mb-2">タスク名</label>
        <input
          type="text"
          name="title"
          class="w-full px-3 py-2 border border-gray-300 rounded-md"
          required
        />
      </div>
      <div class="mb-4">
        <label for="description" class="block text-gray-700 mb-2"
          >タスク詳細</label
        >
        <textarea
          name="description"
          rows="4"
          class="w-full px-3 py-2 border border-gray-300 rounded-md"
          required
        ></textarea>
      </div>
      <div class="mb-4">
        <label for="endtime" class="block text-gray-700 mb-2">期限</label>
        <input
          type="date"
          name="endtime"
          class="w-full px-3 py-2 border border-gray-300 rounded-md"
          required
        />
      </div>
      <div class="flex justify-between items-center pt-4">
        <button
          type="submit"
          class="bg-indigo-500 hover:bg-indigo-600 text-white font-bold p-4 rounded-full"
        >
          作成する
        </button>
        <a href="{{ url_for('root.home') }}" class="text-indigo-500"
          >キャンセル</a
        >
      </div>
    </form>
  </div>
</div>
{% endblock %}

app/templates/task_update.html
{% extends 'layout.html' %} {% block content %}
<div
  class="container mx-auto min-h-screen flex justify-center items-start pt-24"
>
  <div class="bg-white w-full max-w-md p-8 rounded-md shadow">
    <h1 class="text-2xl font-bold mb-6 text-gray-600">タスク編集</h1>
    <form
      action="{{ url_for('root.task_update', task_id=task.id) }}"
      method="POST"
    >
      <div class="mb-4">
        <label for="title" class="block text-gray-700 mb-2">タスク名</label>
        <input
          type="text"
          name="title"
          value="{{ task.title }}"
          class="w-full px-3 py-2 border border-gray-300 rounded-md"
          required
        />
      </div>
      <div class="mb-4">
        <label for="description" class="block text-gray-700 mb-2"
          >タスク詳細</label
        >
        <textarea
          name="description"
          rows="4"
          class="w-full px-3 py-2 border border-gray-300 rounded-md"
          required
        >
{{ task.description }}</textarea
        >
      </div>
      <div class="mb-4">
        <label for="endtime" class="block text-gray-700 mb-2">期限</label>
        <input
          type="date"
          name="endtime"
          value="{{ task.endtime.strftime('%Y-%m-%d') }}"
          class="w-full px-3 py-2 border border-gray-300 rounded-md"
          required
        />
      </div>
      <div class="flex justify-between items-center pt-4">
        <button
          type="submit"
          class="bg-indigo-500 hover:bg-indigo-600 text-white font-bold p-4 rounded-full"
        >
          更新する
        </button>
        <a href="{{ url_for('root.home') }}" class="text-indigo-500"
          >キャンセル</a
        >
      </div>
    </form>
  </div>
</div>
{% endblock %}

app/templates/user_register.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <title>登録</title>
  </head>
  <main>
    <div class="min-h-screen flex items-center justify-center">
      <div class="bg-white p-10 rounded shadow-lg w-full md:w-1/3">
        <h1 class="text-2xl font-semibold mb-6">ユーザー登録</h1>
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %}
        <div
          class="rounded bg-red-200 border-red-500 text-red-900 border-l-4 p-4 mb-4"
          role="alert"
        >
          <p>{{ message }}</p>
        </div>
        {% endfor %} {% endif %} {% endwith %}
        <form action="{{ url_for('root.register') }}" method="post">
          <div class="mb-4">
            <label class="block mb-1 text-gray-700">ユーザー名</label>
            <input
              type="text"
              name="username"
              placeholder="ユーザー名を入力"
              required
              class="w-full border border-gray-300 rounded py-2 px-3 focus:outline-none focus:border-indigo-500"
            />
          </div>
          <div class="mb-4">
            <label class="block mb-1 text-gray-700">Email</label>
            <input
              type="email"
              name="email"
              placeholder="メールアドレスを入力"
              required
              class="w-full border border-gray-300 rounded py-2 px-3 focus:outline-none focus:border-indigo-500"
            />
          </div>
          <div class="mb-4">
            <label class="block mb-1 text-gray-700">パスワード</label>
            <input
              type="password"
              name="password"
              placeholder="パスワードを入力"
              required
              class="w-full border border-gray-300 rounded py-2 px-3 focus:outline-none focus:border-indigo-500"
            />
          </div>
          <div class="flex justify-between items-center pt-4">
            <button
              type="submit"
              class="bg-indigo-500 hover:bg-indigo-600 text-white font-bold p-4 rounded-full"
            >
              ユーザー登録
            </button>
          </div>
        </form>
      </div>
    </div>
  </main>
</html>